### ISSUE TITLE
Scrapy Environment Setting Problems

### ISSUE THREAD

**Issue by k1923456** [BbsonLin/house_crawlers#5]
1. Python library "Twisted" is too new for Scrapy-1.1.0, it will cause this Error:

    ypeError: 'float' object is not iterable
2017-03-09 13:58:34 [scrapy] ERROR: Error downloading <GET http://sale.591.com.tw/>
TypeError: 'float' object is not iterable

2. Solution:

    Uninstall Twisted-17.5 and install Twisted-16.6.0:

    pip uninstall twisted
    pip install twisted==16.6.0

**Comment by BbsonLin** [comment]
Using latest scrapy version will resolve this issue
